{
  imports = [
    ./bootloader.nix
    ./services.nix
    ./sound.nix
    ./zram.nix
    ./env.nix
    ./user.nix
    ./xserver.nix
    ./nm.nix
    ./virtmanager.nix
    ./hyprland.nix
    ./trim.nix
    ./bluetooth.nix
    ./nixvim/nixvim.nix
    ./hardware.nix
    ./virtualbox.nix
  ];
}
